### PR TITLE
feat: support for parsing date restrictions

### PR DESCRIPTION
**Pull request by kvisscher**

### CODE REVIEW

**Comment by kvisscher** [comment]
I just need some help to write a test for this, I know it works in practice, but a test would be nice.

/cc @droyo

**Comment by kvisscher** [comment]
@droyo do you have time to explain to me how I can write a test for this?

**Comment by droyo** [comment]
Hi @kvisscher , thanks for the PR and I'm sorry for not getting back to you until now.

Please take a look at the `xsd/testdata` directory. For each test, it contains two files:

`.xsd`: the schema definition
`.json`: a json encoding of the expected `xsd.Schema` value.

So you can put another pair of files with the input schema specifying a date with min/max restriction and the output json containing the new fields you've defined.

**Comment by ne0h12** [comment]
@droyo ping

**Comment by ne0h12** [comment]
@droyo thanks!

**Pull request merged**
